# -*- coding: utf-8 -*-
"""project-preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qPfS_OU1J0nhr2z6htERrnsPOngVPqAq
"""
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn import tree
from sklearn.ensemble import RandomForestRegressor
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import AdaBoostRegressor
import os
import xgboost as xgb
import math
from sklearn.linear_model import Lasso, TheilSenRegressor
import catboost
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.model_selection import RandomizedSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression, RANSACRegressor
from sklearn.metrics import r2_score, mean_squared_log_error
from sklearn.linear_model import SGDRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import RobustScaler
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.linear_model import ElasticNet, HuberRegressor
import lightgbm

DEBUG = False

train_data = pd.read_csv("train.csv")
test_data = pd.read_csv("test.csv")
PREDICT_COL_NAME = "SalePrice"
train_data.head()

# Checking which features have how many null values for preprocessing
temp_data = train_data
temp_data2 = test_data
null_count = temp_data.isnull().sum()
null_count2 = temp_data2.isnull().sum()

init_size = len(temp_data.columns)
print(init_size)
for index, value in null_count.items():
    if(value > 0): # printing features that have more than 0 null values
        # printing null value count and the ratio of null to filled values
        if DEBUG:
            print(str(index) + " value: " + str(value) + " ratio: " + str(round((value / len(temp_data) * 100), 2)) + "%")
        
        # dropping features whose given data is mostly just null values - threshold is 75%
        if((value / len(temp_data)) >= 0.75):
            if DEBUG:
                print("dropping: " + index)
            temp_data = temp_data.drop(columns=index)

print("Dropped: " + str(init_size - len(temp_data.columns)) + " columns")

for index, value in null_count2.items():
    if(value > 0): # printing features that have more than 0 null values
        # printing null value count and the ratio of null to filled values
        if DEBUG:
            print(str(index) + " value: " + str(value) + " ratio: " + str(round((value / len(temp_data2) * 100), 2)) + "%")
        
        # dropping features whose given data is mostly just null values - threshold is 75%
        if((value / len(temp_data2)) >= 0.75):
            if DEBUG:
                print("dropping: " + index)
            temp_data2 = temp_data2.drop(columns=index)

print("Dropped: " + str(init_size - len(temp_data2.columns)) + " columns")

# Collecting remaining feature names that have null value
null_count = temp_data.isnull().sum()
null_count2 = temp_data2.isnull().sum()
null_cols = []
null_cols2 = []
for index, value in null_count.items():
    simpleImputer = SimpleImputer(strategy='mean', missing_values=np.nan)
    if(value > 0): # printing features that have more than 0 null values
        null_cols.append(index)

for index, value in null_count2.items():
    simpleImputer = SimpleImputer(strategy='mean', missing_values=np.nan)
    if(value > 0): # printing features that have more than 0 null values
        null_cols2.append(index)

# label encoding before filling null values

catergoies = temp_data.select_dtypes(exclude=["number"])
catergoies2 = temp_data2.select_dtypes(exclude=["number"])

print(catergoies.columns)
print(catergoies2.columns)

class_le = LabelEncoder()
for value in catergoies.columns:
#     print(value)
    temp_data[value] = class_le.fit_transform(temp_data[value].values)

for value in catergoies2.columns:
#     print(value)
    temp_data2[value] = class_le.fit_transform(temp_data2[value].values)

# Filling empty values with the mean values
if DEBUG:
    print(null_cols)
simpleImputer = SimpleImputer(strategy='mean', missing_values=np.nan)
simpleImputer = simpleImputer.fit(temp_data[null_cols])
temp_data[null_cols] = simpleImputer.transform(temp_data[null_cols])

simpleImputer2 = SimpleImputer(strategy='mean', missing_values=np.nan)
simpleImputer2 = simpleImputer.fit(temp_data2[null_cols2])
temp_data2[null_cols2] = simpleImputer.transform(temp_data2[null_cols2])

train_data = temp_data
train_data2 = temp_data2
train_data.head()

# Removing sale price and setting it as Y value  -- no need to do this for the testing data (no sale price)
Y_value = train_data[PREDICT_COL_NAME]
train_data = train_data.drop([PREDICT_COL_NAME], axis=1)

# Using a pair-wise correlation matrix to remove highly correlated feature (where value of either of those features can be estimated with just one value) - adapted from https://towardsdatascience.com/how-to-use-pairwise-correlation-for-robust-feature-selection-20a60ef7d10
matrix = train_data.corr()
matrix2 = train_data2.corr()#

plt.figure(figsize=(16,12))

_ = sns.heatmap(matrix)

# getting highly correlated columns
mask = np.triu(np.ones_like(matrix, dtype=bool))
mask2 = np.triu(np.ones_like(matrix2, dtype=bool))

reduced_matrix = matrix.mask(mask)
reduced_matrix2 = matrix2.mask(mask2)

cols_drop = [c for c in reduced_matrix.columns if any(reduced_matrix[c] > 0.85)]
cols_drop2 = [c for c in reduced_matrix2.columns if any(reduced_matrix2[c] > 0.85)]

if DEBUG:
    print(cols_drop)
train_data = train_data.drop(cols_drop, axis=1)
train_data2 = train_data2.drop(cols_drop2, axis=1)

if DEBUG:
    print(train_data.head())

# Seeing correlation factor between the retained values and the final sale price
matrix_cols = pd.concat([train_data, Y_value], axis=1) #nothing to concat for test matrix

# getting the correlation
Y_correlation = matrix_cols.corr()
# print(len(Y_correlation))
price_correlations = Y_correlation[len(Y_correlation)-1 : ]

# dropping the last column as that's the correlation between the sale price with the sale price (so it's always 1)
price_correlations = price_correlations.iloc[:, :-1]

# making all values positive
for index, value in price_correlations.items():
    price_correlations[index] = abs(value)
    if DEBUG:
        print(index + ": " + str(abs(value[PREDICT_COL_NAME])))

print(price_correlations)
###
# retaining features who correlations to sales price is greater than 50%
to_retain = [x for x, value in price_correlations.items() if value[PREDICT_COL_NAME] >= 0.02]

print("retaining these columns because of good correlation with the prediction feature: " + str(to_retain))
X_value = train_data[to_retain]
X_value2 = train_data2[to_retain] ##retaining same features for testing data
if DEBUG:
    print(X_value)

# correlation matrix of the retain values to the sale price (focus on last column)
matrix_cols = pd.concat([X_value, Y_value], axis=1)

# getting the correlation
Y_correlation = matrix_cols.corr()
plt.figure(figsize=(16,12))

_ = sns.heatmap(Y_correlation)

# Visualizing them
plt.subplots(figsize=(20, 20))
for index_itr, col in enumerate(to_retain):
    plt.subplot(int(math.sqrt(len(to_retain))) + 1, int(math.sqrt(len(to_retain))) + 1, index_itr+1)
    plt.scatter(x=matrix_cols[col], y=matrix_cols[PREDICT_COL_NAME])
    plt.xlabel(col)
    plt.ylabel(PREDICT_COL_NAME)
    
plt.show()

# print("\n#---------------------------------------------------------------------------------------------#\n")
X_train, X_test, Y_train, Y_test = train_test_split(X_value, Y_value, test_size = 0.10, random_state=42)
print()

# Random Forest
# n_estimators = [x for x in range(200, 2200, 200)]
# max_features = ['auto', 'sqrt', 'log2']
# max_depth = [5, 7, 8, 10 , 12, 15, 20, 25, 30, 50, 60, 80, 100, None]
# min_samples_split = [2,3,5,7,10]
# min_samples_leaf = [1,2,3,4,5]
# bootstrap = [True, False]


# RF_Grid = {'n_estimators' : n_estimators, 'max_depth' : max_depth, 'min_samples_split' : min_samples_split,
#             'min_samples_leaf' : min_samples_leaf, 'max_features' : max_features, 'bootstrap' : bootstrap}
# grid_search = RandomizedSearchCV(estimator = RandomForestRegressor(), param_distributions =RF_Grid, n_iter=150,cv=3, scoring = 'neg_root_mean_squared_error', verbose=0, n_jobs=-1)

# RFR = grid_search.fit(X_train,Y_train)
# optimal = RFR.best_params_
# print("n_estimators ", optimal["n_estimators"])
# print("max_features ", optimal["max_features"])
# print("max_depth ", optimal["max_depth"])
# print("min_samples_split", optimal["min_samples_split"])
# print("min_samples_leaf", optimal["min_samples_leaf"])
# print("bootstrap ", optimal["bootstrap"])
# print()
# R = RandomForestRegressor()
# RFR = RandomizedSearchCV(estimator = R, param_distributions = RF_Grid, n_iter = 100, cv = 3, n_jobs = -1 , verbose = 2)
# print(RFR.best_params_)

# RFR = RandomForestRegressor(n_estimators = optimal["n_estimators"], max_features = optimal["max_features"]
#                             ,max_depth = optimal["max_depth"], min_samples_split=optimal["min_samples_split"], 
#                             min_samples_leaf=optimal["min_samples_leaf"], bootstrap=optimal["bootstrap"]) #default number of estimators = 100
#

# RFR = RandomForestRegressor(n_estimators = 1000, max_features = 'sqrt',
#                             max_depth = 12, bootstrap = False) 
# RFR_Cross_Score = cross_val_score(RFR, X_train, Y_train, cv=10, scoring = 'neg_mean_squared_log_error') #cross validation 

# RFR.fit(X_train, Y_train)
# RFR_prediction = RFR.predict(X_test)
# RfrScore = RFR.score(X_test, Y_test) #R^2 coefficient score
# Rfr_RMSE = mean_squared_error(Y_test, RFR_prediction, squared=False) #RMSE score

# RFR_error = abs(RFR_prediction - Y_test)
# RFR_MAPE = np.mean(100*(RFR_error/Y_test))
# RFR_R2 = r2_score(Y_test, RFR_prediction)
# RFR_RMSLE= mean_squared_log_error(Y_test, RFR_prediction, squared = False)


# print("Random Forest Regressor")
# print("10-Fold Avg RMSLE ", math.sqrt(abs(np.mean(RFR_Cross_Score))))
# print("Current Run Mean RMSE: ", Rfr_RMSE)
# print("R2 Coefficient Score: ", round(RFR_R2, 2))
# print("Accuracy (100 - MAPE): ", round(100-RFR_MAPE, 2), "%")
# print("RMSLE ", RFR_RMSLE)
# print()

# RFR_prediction_final = RFR.predict(X_value2)
# RFR_submission = pd.DataFrame(columns = ['Id' , 'SalePrice'])
# RFR_submission['Id'] = [x for x in range(1461,2920)]
# RFR_submission['SalePrice'] = RFR_prediction_final
# RFR_submission.to_csv('RFR_submission.csv', index= False)

#Extra Tree Regressor------------------------------------------------------------------------------------------
# ETR = ExtraTreesRegressor(bootstrap=False, criterion='rmse', max_depth=10,
#                     max_features='auto', max_leaf_nodes=None, min_impurity_decrease=0.0, min_samples_split=2,n_estimators=350, oob_score=False, verbose=0,
#                     warm_start=False)
#                    
# ETR_Cross_Score = cross_val_score(ETR, X_train, Y_train, cv=10, scoring = 'neg_mean_squared_log_error') #cross validation 

# ETR.fit(X_train, Y_train)
# ETR_prediction = ETR.predict(X_test)
# ETRScore = ETR.score(X_test, Y_test) #R^2 coefficient score
# ETR_RMSE = mean_squared_error(Y_test,ETR_prediction, squared=False) #RMSE score

# ETR_error = abs(ETR_prediction - Y_test)
# ETR_MAPE = np.mean(100*(ETR_error/Y_test))
# ETR_R2 = r2_score(Y_test, ETR_prediction)
# ETR_RMSLE= mean_squared_log_error(Y_test, ETR_prediction, squared = False)


# print("ExtraTreesRegressor Regressor")
# print("10-Fold Avg RMSLE ", math.sqrt(abs(np.mean(ETR_Cross_Score))))
# print("Current Run Mean RMSE: ", ETR_RMSE)
# print("R2 Coefficient Score: ", round(ETR_R2, 2))
# print("Accuracy (100 - MAPE): ", round(100-ETR_MAPE, 2), "%")
# print("RMSLE ", ETR_RMSLE)
# print()

# ETR_prediction_final = ETR.predict(X_value2)
# ETR_submission = pd.DataFrame(columns = ['Id' , 'SalePrice'])
# ETR_submission['Id'] = [x for x in range(1461,2920)]
# ETR_submission['SalePrice'] = ETR_prediction_final
# ETR_submission.to_csv('ETR_submission.csv', index= False)
#Decision Tree-------------------------------------------------------------------------------------------------
# X_DT = SelectKBest(chi2,k=8).fit(X_value,Y_value)
# best_features = []


# for bool, feature in zip(X_DT.get_support(), X_value.columns):
#     if bool:
#         best_features.append(feature)
 
# X_DT = SelectKBest(chi2,k=8).fit_transform(X_value,Y_value)
# X_finalDT = pd.DataFrame(data = X_DT, columns = best_features)

# X_trainDT, X_testDT, Y_trainDT, Y_testDT = train_test_split(X_finalDT, Y_value, test_size = 0.10, random_state=42)



# DT = tree.DecisionTreeRegressor(splitter = "best", max_depth=(5) )
# DT_Cross_Score = cross_val_score(DT, X_trainDT, Y_trainDT, cv=10, scoring = 'neg_mean_squared_log_error') #cross validation 

# DT.fit(X_trainDT, Y_trainDT)
# DT_prediction = DT.predict(X_testDT)
# DTScore = DT.score(X_testDT, Y_testDT) #R^2 coefficient score
# DT_RMSE = mean_squared_error(Y_testDT, DT_prediction, squared=False) #RMSE score

# DT_error = abs(DT_prediction - Y_testDT)
# DT_MAPE = np.mean(100*(DT_error/Y_testDT))
# DT_R2 = r2_score(Y_testDT, DT_prediction)
# DT_RMSLE= mean_squared_log_error(Y_test, DT_prediction, squared = False)

# print("Decision Tree Regressor")
# print("10-Fold Avg RMSLE ",math.sqrt( abs(np.mean(DT_Cross_Score))))
# print("Current Run Mean RMSE: ", DT_RMSE)
# print("R2 Coefficient Score: ", round(DT_R2, 2))
# print("Accuracy (100 - MAPE): ", round(100-DT_MAPE, 2), "%")
# print("RMSLE ", DT_RMSLE)
# print()

# Adaptive Boosting (AdaBoosting)------------------------------------------------------------------------------
# ABR = AdaBoostRegressor(n_estimators = 50, learning_rate = 0.2, loss='exponential')
# ABR_Cross_Score = cross_val_score(ABR, X_train, Y_train, cv=10, scoring = 'neg_mean_squared_log_error') #cross validation

# ABR.fit(X_train, Y_train)
# ABR_prediction = ABR.predict(X_test)
# AbrScore = ABR.score(X_test, Y_test) #R^2 coefficient score
# Abr_RMSE = mean_squared_error(Y_test, ABR_prediction, squared=False) #RMSE score

# ABR_error = abs(ABR_prediction - Y_test)
# ABR_MAPE = np.mean(100*(ABR_error/Y_test))
# ABR_R2 = r2_score(Y_test, ABR_prediction)
# ABR_RMSLE= mean_squared_log_error(Y_test, ABR_prediction, squared = False)

# print("AdaBoost Regressor")
# print("10-Fold Avg RMSLE ", math.sqrt(abs(np.mean(ABR_Cross_Score))))
# print("Current Run Mean RMSE: ", Abr_RMSE)
# print("R2 Coefficient Score: ", round(ABR_R2, 2))
# print("Accuracy (100 - MAPE): ", round(100-ABR_MAPE, 2), "%")
# print("RMSLE ", ABR_RMSLE)
# print()

# LightGBM (LGBM)------------------------------------------------------------------------------

# LGB = lightgbm.LGBMRegressor(objective = 'regression')
# LGB_parameters = {'boosting_type': ['dart'], 'num_leaves': [20, 30, 40, 50, 100, 200, 300, 500, 1000,2000,5000,10000], 'max_depth': [-1, 4, 6, 9, 12, 15, 20, 30, 50, 70, 100],'learning_rate':[0.01, 0.05, 0.1, 0.2, 0.4, 0.5], 'n_estimators':[100, 300, 500, 700, 800, 1000, 1200, 1500, 2000, 3000, 5000] }
# LGB_grid = RandomizedSearchCV(estimator = LGB, param_distributions = LGB_parameters, n_iter=250, cv=3,scoring ='neg_mean_squared_log_error', verbose=0, n_jobs=-1 )


# LGB = LGB_grid.fit(X_train,Y_train)
# optimal = LGB.best_params_

# print("LGBM")
# print("num_leaves: ", optimal["num_leaves"])
# print("max_depth: ", optimal["max_depth"])
# print("learning rate: ", optimal["learning_rate"])
# print("n_estimators: ", optimal["n_estimators"])
##
# LGB = lightgbm.LGBMRegressor(num_leaves = 30, max_depth = 4, learning_rate= 0.2, n_estimators = 300, boosting_type= 'dart')

# LGB_Cross_Score = cross_val_score(LGB, X_train, Y_train, cv=10,scoring = 'neg_mean_squared_log_error') #cross validation
# LGB.fit(X_train, Y_train)
# LGB_prediction = LGB.predict(X_test)
# # LGB_prediction = np.exp(LGB_prediction)
# LGBScore = LGB.score(X_test, Y_test) #R^2 coefficient score
# LGB_RMSE = mean_squared_error(Y_test, LGB_prediction, squared=False) #RMSE score

# LGB_error = abs(LGB_prediction - Y_test)
# LGB_MAPE = np.mean(100*(LGB_error/Y_test))
# LGB_R2 = r2_score(Y_test, LGB_prediction)
# LGB_RMSLE= mean_squared_log_error(Y_test, LGB_prediction, squared = False)

# print("Light GBM")
# print("10-Fold Avg RMSLE ", math.sqrt(abs(np.mean(LGB_Cross_Score))))
# print("Current Run Mean RMSE: ", LGB_RMSE)
# print("R2 Coefficient Score: ", round(LGB_R2, 2))
# print("Accuracy (100 - MAPE): ", round(100-LGB_MAPE, 2), "%")
# print("RMSLE ", LGB_RMSLE)
# print()

# Gradient Boosting (XGBoost)---------------------------------------------------
# XGB_parameters = {'n_estimators': [100, 200, 500, 1000], 'max_depth': [3, 5, 7, 10, 12, 15], 'grow_policy': [0, 1],
#                   'learning_rate' : [ 0.05, 0.1, 0.2, 0.3, 0.5],'objective': ['reg:squarederror'], 'booster' : ['gbtree', 'gblinear', 'dart'],
#                   'eval_metric': ['rmse'], 'colsample_bytree': [0.2, 0.5, 0.6, 0.8, 1], 'tree_method': ['exact'] ,'subsample': [0.5, 0.6, 0.8, 1]}
                    

# XGB_grid = RandomizedSearchCV(estimator = xgb.XGBRegressor(), param_distributions = XGB_parameters,n_iter=100,cv=3,scoring ='neg_root_mean_squared_error', verbose=0, n_jobs=-1)
# XGB = XGB_grid.fit(X_train,Y_train)
# optimal = XGB.best_params_
# print("n_estimators ", optimal["n_estimators"])
# print("max_depth ", optimal["max_depth"])
# print("grow_policy ", optimal["grow_policy"])
# print("learning_rate ", optimal["learning_rate"])
# print("objective ", optimal["objective"])
# print("booster ", optimal["booster"])
# print("colsample_bytree ", optimal["colsample_bytree"])
# print("subsample ", optimal["subsample"])
# print()

# XGB = xgb.XGBRegressor(n_estimators = optimal["n_estimators"], max_depth = optimal["max_depth"], grow_policy = optimal["grow_policy"],
#                        learning_rate = optimal["learning_rate"], booster = optimal["booster"], eval_metric = 'rmse', colsample_bytree = optimal["colsample_bytree"],
#                        tree_method = 'exact',subsample = optimal["subsample"], objective = 'reg:squarederror')
XGB = xgb.XGBRegressor(booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.4, enable_categorical=False, gpu_id=-1, importance_type=None, learning_rate=0.004, max_delta_step=0,
              max_depth=5, min_child_weight=1,monotone_constraints='()', n_estimators=4500, n_jobs=-1,
              num_parallel_tree=1, predictor='auto', reg_alpha=3,reg_lambda=3, scale_pos_weight=1, subsample=0.65,
              tree_method='exact', verbosity=None)
XGB_Cross_Score = cross_val_score(XGB, X_train, Y_train, cv=10,scoring = 'neg_mean_squared_log_error')

XGB.fit(X_train, Y_train)
XGB_prediction = XGB.predict(X_test)
XGB_RMSE = mean_squared_error(Y_test, XGB_prediction, squared = False)

XGB_error = abs(XGB_prediction - Y_test)
XGB_MAPE = np.mean(100*(XGB_error/Y_test))
XGB_R2 = r2_score(Y_test, XGB_prediction)
XGB_RMSLE= mean_squared_log_error(Y_test, XGB_prediction, squared = False)

print("XGBoost Regressor")
print("10-Fold Avg RMSLE ", math.sqrt(abs(np.mean(XGB_Cross_Score))))
print("Current Run Mean RMSE: ", XGB_RMSE)
print("R2 Coefficient Score: ", round(XGB_R2, 2))
print("Accuracy (100 - MAPE): ", round(100-XGB_MAPE, 2), "%")
print("RMSLE ", XGB_RMSLE)
print()

XGB_prediction_final = XGB.predict(X_value2)
XGB_submission = pd.DataFrame(columns = ['Id' , 'SalePrice'])
XGB_submission['Id'] = [x for x in range(1461,2920)]
XGB_submission['SalePrice'] = XGB_prediction_final
XGB_submission.to_csv('XGB_submission.csv', index= False)

# Gradient Boosting (CatBoost)--------------------------------------------------------------------------------------------

CB = catboost.CatBoostRegressor(loss_function = 'RMSE', silent = True)
CB_parameters = {'iterations' : [50, 100, 150, 200, 300, 500, 1000], 'learning_rate' : [0.03, 0.05, 0.1], 'depth': [2, 4, 6, 8, 10], 'l2_leaf_reg' : [0.2, 0.5, 1, 3]}
CB_grid = RandomizedSearchCV(estimator = CB, param_distributions = CB_parameters,n_iter=150,cv=3,scoring ='neg_root_mean_squared_error', verbose=0, n_jobs=-1)

fit_grid = CB_grid.fit(X_train,Y_train)
optimal = fit_grid.best_params_

print("iterations ", optimal["iterations"])
print("learning_rate ", optimal["learning_rate"])
print("depth ", optimal["depth"])
print("l2_leaf_reg", optimal["l2_leaf_reg"])
iterations = 700
CB = catboost.CatBoostRegressor(iterations = 750,  learning_rate = 0.04, depth = 5, l2_leaf_reg = 0.4, loss_function = 'RMSE', silent = True)
# CB = catboost.CatBoostRegressor(iterations = optimal["iterations"], learning_rate =optimal["learning_rate"], depth =optimal["depth"], l2_leaf_reg = optimal["l2_leaf_reg"], loss_function = 'RMSE', silent = True)
# CB.grid_search(CB_grid,X_train, y=Y_train, cv = 5)

CB_Cross_Score = cross_val_score(CB, X_train, Y_train, cv=10,scoring = 'neg_mean_squared_log_error')
CB.fit(X_train, Y_train, silent = True)

CB_prediction = CB.predict(X_test)
CB_RMSE = mean_squared_error(Y_test, CB_prediction, squared = False)
CB_RMSLE= mean_squared_log_error(Y_test, CB_prediction, squared = False)

CB_error = abs(CB_prediction - Y_test)
CB_MAPE = np.mean(100*(CB_error/Y_test))
CB_R2 = r2_score(Y_test, CB_prediction)
print("CatBoost Regressor")
print("10-Fold Avg RMSLE ", math.sqrt(abs(np.mean(CB_Cross_Score))))
print("Current Run Mean RMSE: ", CB_RMSE)
print("R2 Coefficient Score: ", round(CB_R2,2))
print("Accuracy (100 - MAPE): ", round(100-CB_MAPE, 2), "%")
print("RMSLE ", CB_RMSLE)
print()

CB_prediction_final = CB.predict(X_value2)
CB_submission = pd.DataFrame(columns = ['Id' , 'SalePrice'])
CB_submission['Id'] = [x for x in range(1461,2920)]
CB_submission['SalePrice'] = CB_prediction_final
CB_submission.to_csv('cat_submission.csv',  index= False)

# #Linear Regression ----------------------------------------------------------------------------------------------------------------
LR = LinearRegression()
LR_Cross_Score = cross_val_score(LR, X_train, Y_train, cv=10,scoring = 'neg_mean_squared_log_error')

LR.fit(X_train, Y_train)
LR_prediction = LR.predict(X_test)
LR_RMSE = mean_squared_error(Y_test, LR_prediction, squared= False)
LR_RMSLE= mean_squared_log_error(Y_test, LR_prediction, squared = False)
LR_error = abs(LR_prediction - Y_test)
LR_MAPE = np.mean(100*(LR_error/Y_test))
LR_R2 = r2_score(Y_test, LR_prediction)
print("Linear Regressor")
print("10-Fold Avg RMSLE ", math.sqrt(abs(np.mean(LR_Cross_Score))))
print("Current Run Mean RMSE: ", LR_RMSE)
print("R2 Coefficient Score: ", round(LR_R2, 2))
print("Accuracy (100 - MAPE): ", round(100-LR_MAPE, 2), "%")
print("RMSLE ", LR_RMSLE)
print()

#RANSAC Regression--------------------------------------------------------------------------------------------------------------------

# RAN = RANSACRegressor(loss = 'squared_error')
# RAN_Cross_Score = cross_val_score(RAN, X_train, Y_train, cv=5,scoring = 'neg_mean_squared_log_error')

# RAN.fit(X_train, Y_train)
# RAN_prediction = RAN.predict(X_test)
# RAN_RMSE = mean_squared_error(Y_test, RAN_prediction, squared= False)

# RAN_error = abs(RAN_prediction - Y_test)
# RAN_MAPE = np.mean(100*(RAN_error/Y_test))
# RAN_R2 = r2_score(Y_test, RAN_prediction)

# print("RANSAC Regressor")
# print("5-fold Cross Validation Scores:")
# print("5-Fold Avg RMSE ", math.sqrt(abs(np.mean(RAN_Cross_Score))))
# print("Current Run Mean RMSE: ", RAN_RMSE)
# print("R2 Coefficient Score: ", round(RAN_R2, 2))
# print("Accuracy (100 - MAPE): ", round(100-RAN_MAPE, 2), "%")

# print()
#Support Vector Regression-----------------------------------------------------------------------------------------------------------
# SVR = SVR()
# SVR_Cross_Score = cross_val_score(SVR, X_train, Y_train, cv=10, scoring = 'neg_mean_squared_log_error')

# SVR.fit(X_train, Y_train)
# SVR_prediction = SVR.predict(X_test)
# SVR_RMSE = mean_squared_error(Y_test, SVR_prediction, squared= False)

# SVR_error = abs(SVR_prediction - Y_test)
# SVR_MAPE = np.mean(100*(SVR_error/Y_test))
# SVR_R2 = r2_score(Y_test, SVR_prediction)

# print("Support Vector Regressor")
# print("10-fold Cross Validation Scores:")
# print("10-Fold Avg RMSLE ", math.sqrt(abs(np.mean(SVR_Cross_Score))))
# print("Root Mean Squared Error: ", SVR_RMSE)
# print("R2 Coefficient Score: ", round(SVR_R2, 2))
# print("Accuracy (100 - MAPE): ", round(100-SVR_MAPE, 2), "%")
# print()


#Lasso Regressor----------------------------------------------------------------------------------------------------------------------
# LAS = HuberRegressor(max_iter=2000)
# LAS_Cross_Score = cross_val_score(LAS, X_train, Y_train, cv=10)

# LAS.fit(X_train, Y_train)
# LAS_prediction = LAS.predict(X_test)
# LAS_RMSE = mean_squared_error(Y_test, LAS_prediction, squared = False)
# LAS_RMSLE= mean_squared_log_error(Y_test, LAS_prediction, squared = False)
# LAS_error = abs(LAS_prediction - Y_test)
# LAS_MAPE = np.mean(100*(LAS_error/Y_test))
# LAS_R2 = r2_score(Y_test, LAS_prediction)
# print("Lasso Regressor")
# print("10-Fold Avg RMSLE ", abs(np.mean(LAS_Cross_Score)))
# print("Current Run Mean RMSE: ", LAS_RMSE)
# print("R2 Coefficient Score: ", round(LAS_R2, 2))
# print("Accuracy (100 - MAPE): ", round(100-LAS_MAPE, 2), "%")
# print("RMSLE ", LAS_RMSLE)
# print()


# LAS_prediction_final = LAS.predict(X_value2)
# LAS_submission = pd.DataFrame(columns = ['Id' , 'SalePrice'])
# LAS_submission['Id'] = [x for x in range(1461,2920)]
# LAS_submission['SalePrice'] = LAS_prediction_final
# LAS_submission.to_csv('LAS_submission.csv', index= False)







