// Author: Ronaldo Engelke Cunha
// Class: CAP 5725
// Assignment: Assignment 1
// Date: 09/09/2022

#include <iostream>
#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/mat4x4.hpp>
#include <glm/common.hpp>
#include <vector>
#include <Math.h>  
#include <cmath>
#include <stb_image.h>
#include <glm/gtc/type_ptr.hpp>

#define Pi 3.1415926535897932384626433832795

//vertex shader - processes input vertex data, usually normalizes and transforms input data to coordinates that fall within OpenGL's visible region
std::string vertexShaderProg = R"(#version 330 core
layout (location = 0) in vec3 position; 
layout (location = 1) in vec3 normal; 
layout (location = 2) in vec2 uv; 
uniform mat4 view, projection, model; 
out vec3 fragNormal, fragPosition;
out vec2 fragUV;
void main()
{
	vec4 mPosition = model * vec4(position, 1.0);
	fragPosition = mPosition.xyz;
	mat3 normalMatrix = transpose(inverse(mat3(model)));
	fragNormal = normalMatrix * normal;
	gl_Position = projection * view * mPosition;
	fragUV = uv;
})";

//fragment shader - calculates the color output of our pixels. Processes a fragment generated by the rasterization stage, into a set of colors and a single depth value.
std::string fragmentShaderProg = R"(#version 330 core
in vec3 fragNormal, fragPosition;
in vec2 fragUV;
uniform sampler2D diffuseTex; 
uniform vec4 light; //DONE
uniform vec3 materialSpecularColor, cameraPosition; 
uniform float Kd, Ks, shininess; 
out vec4 outColor;

vec3 computeColor();

void main()
{
	outColor = vec4(computeColor(), 1);
};

vec3 computeColor()
{
	vec4 materialColor = texture(diffuseTex, fragUV);
	vec3 lightVector = light.xyz;
	
	if(light.w > 0)
		lightVector = light.xyz - fragPosition; 

	vec3 L = normalize(lightVector);
	vec3 N = normalize(fragNormal);

	vec3 V = normalize(cameraPosition - fragPosition);
	vec3 H = normalize (L + V);
	
	vec3 ambientLightIntensity = vec3(0.1f, 0.1f, 0.1f);
	vec3 ambientReflection = ambientLightIntensity * vec3(materialColor.xyz);

	vec3 diffuseReflection = Kd * vec3(materialColor.xyz) * clamp(dot(L,N), 0, 1);
	vec3 specularReflection = Ks * materialSpecularColor * pow(clamp(dot(N,H), 0, 1), shininess);

	return diffuseReflection + specularReflection + ambientReflection;
}
)";

std::vector<GLfloat> vertices;
std::vector<GLfloat> texCoordinates;
std::vector<GLfloat> normals;
std::vector<GLuint> indices;
std::vector<GLuint> normalIndices;

glm::vec4 lightPos;
glm::vec3 cameraUp, cameraPos, cameraFront;
glm::vec3 matSpecColor = glm::vec3(0.992157f, 0.941176f, 0.807843f); //default brass
float yaw = -90.0f;
float pitch, Radius;
float pitchL, yawL;
float camX, camY, camZ, Ks = 0.6f, Kd=0.4f, shininess=10.0f;

/// <summary>
/// Resize callback function for when window is resized by user. This adjusts the viewpoirt when the user resizes the window.
/// This function takes a window, and new window dimensions as parameters. Whenever the window changes in size, GLFW calls this function and fills in the proper arguments for you to process.
/// </summary>
/// <param name="window"></param>
/// <param name="width"></param>
/// <param name="height"></param>
void framebuffer_size_callback(GLFWwindow* window, int width, int height);

/// <summary>
/// Processes user input.
/// Processes user input.
/// </summary>
/// <param name="window"></param>
void processInput(GLFWwindow* window);

//unsigned int& processVertexArrayObject();
//unsigned int& processVertexBufferObject();
//unsigned int& processElementBufferObject();

unsigned int compileShader(GLenum shaderType, const char* shaderProgram);
unsigned int compileCompleteShaders(const char* vertexShader, const char* fragmentShader);

int main()
{
	glfwInit();
	glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
	glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
	glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

	GLFWwindow* window = glfwCreateWindow(800, 600, "LearnOpenGL", NULL, NULL);

	if (window == NULL)
	{
		std::cout << "Failed to create GLFW window" << std::endl;
		glfwTerminate();
		return -1;
	}

	glfwMakeContextCurrent(window); //tell GLFW to make the context of our window the main context on the current thread

	if (glewInit() != GLEW_OK) //pass GLEW the function to load the address of the OpenGL function pointers which is OS-specific
	{
		std::cout << "Failed to initialize GLEW" << std::endl;
		return -1;
	}
	int width, height;
	width = 800;
	height = 600;
	glViewport(0, 0, width, height);

	glfwSetFramebufferSizeCallback(window, framebuffer_size_callback);

	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	Radius = 1;
	float x, y, z; //coordinates of each vertex
	float u, v; //u represents the unit longitudes of our sphere, v represents the unit latitudes of our sphere
	float Longs = 50;
	float LongsStep; //size of each sector
	float Lats = 50;
	float LatsStep; //size of each stack
	float totalSize = (Longs + 1) * Lats * 2 * 3;

	LongsStep = 2 * Pi / Longs; //calculate the size of each longitude step
	LatsStep = Pi / Lats; //calculate the size of each latitude step

	float LongAngle; //Theta = 2pi * longStep/longCount so also equal to => j * longStep (size)
	float LatAngle; //Phi = (Pi/2 - Pi) * (latStep/latCount) so also equal to => Pi/2 - i * latStep (size)

	const float UnitLat = 1 / (float)(Lats - 1);
	const float UnitLong = 1 / (float)(Longs - 1);

	float normalizedLength = 1.0f;

	//If the Longitude is varying from - 180 to 180 degree then linearly map Longitude = = 180 degree to u = -0.5 and Longitude = 180 to u = 0.5.

	//If the latitude is varying from + 90 to - 90 degrees then linearly map Latitude = -90 degree to v = -0.5 and Latitude = 90 
	//to v = 0.5.If you are using spherical coordinate angles
	//(see https ://en.wikipedia.org/wiki/Spherical_coordinate_systemLinks to an external site.) 
	//then use a similar linear mapping from phi angle to u and theta angle to v.
	std::vector<float> longAngles;
	std::vector<float> testu;
	std::vector<float> testv;

	std::vector<float> latAngles;
	int k0, k1, k2;
	for (int i = 0; i <= Lats; i++)
	{
		LatAngle = (0.5 * Pi) - i * LatsStep; //theta
		latAngles.push_back(LatAngle);
		k1 = i * (Longs + 1);     // beginning of current stack
		k2 = (i + 1) * (Longs + 1);      // beginning of next stack

		for (int j = 0; j <= Longs; j++)
		{
			LongAngle = j * LongsStep; //phi
			longAngles.push_back(LongAngle);
			float LongAngleOfNextLong;
			if (j + 1 > Longs)
			{
				LongAngleOfNextLong = 0;
			}
			else
			{
				LongAngleOfNextLong = (j + 1) * LongsStep;
			}
			float x1, y1, z1;

			//vertex positions
			x = Radius * cos(LatAngle) * cos(LongAngle);
			y = Radius * cos(LatAngle) * sin(LongAngle);
			z = Radius * sin(LatAngle);

			glm::vec3 normal((x * (1.0f) / Radius), (y * (1.0f) / Radius), (z * (1.0f)) / Radius);
			normals.push_back(normal.x);
			normals.push_back(normal.y);
			normals.push_back(normal.z);

			x1 = Radius * cos(LatAngle) * cos(LongAngleOfNextLong);
			y1 = Radius * cos(LatAngle) * sin(LongAngleOfNextLong);
			z1 = Radius * sin(LatAngle);
			glm::vec3 nextLong(x1, y1, z1);

			vertices.push_back(x);
			vertices.push_back(y);
			vertices.push_back(z);
		
			//texture coordinates
			u =(float) (j / Longs);
			v =(float) (i / Lats);
			
			texCoordinates.push_back(u);
			texCoordinates.push_back(v);
		}
	}
	int counter = 0;

	for (int i = 0; i <= Lats; i++)
	{
		k1 = i * (Longs + 1);     // beginning of current stack
		k2 = (i + 1) * (Longs + 1);      // beginning of next stack

		for (int j = 0; j <= Longs; j++, counter++, k1++, k2++)
		{
			//must draw our triangles, then draw our TBN vector protrouding out

			// 2 triangles per sector excluding first and last stacks
			if (i != 0)
			{
				indices.push_back(k1);
				indices.push_back(k2);
				indices.push_back(k1 + 1);
			}

			if (i != (Lats))
			{
				indices.push_back(k1 + 1);
				indices.push_back(k2);
				indices.push_back(k2 + 1);
			}
		}
	}

	//image loading--------------------------------------------------------------------------------------------//

	int imgWidth, imgHeight, channels;
	//stbi_set_flip_vertically_on_load(true);
	unsigned char* img = stbi_load("earth.jpg", &imgWidth, &imgHeight, &channels, 0);

	if (img == NULL)
	{
		printf("Error in loading the image \n");
		exit(1);
	}

	unsigned int VAO;
	glGenVertexArrays(1, &VAO);
	glBindVertexArray(VAO);

	unsigned int VBO;
	glGenBuffers(1, &VBO);
	glBindBuffer(GL_ARRAY_BUFFER, VBO);
	glBufferData(GL_ARRAY_BUFFER, vertices.size() * sizeof(GLfloat), &vertices[0], GL_STATIC_DRAW);

	GLint vertexPositionAttribute;

	glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 0, 0);
	glEnableVertexAttribArray(0);

	unsigned int EBO;
	glGenBuffers(1, &EBO);
	glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, EBO);
	glBufferData(GL_ELEMENT_ARRAY_BUFFER, indices.size() * sizeof(GLuint), &indices[0], GL_STATIC_DRAW);

	//normals----------------------------------------------------------------------------------------------------
	unsigned int VBO_normals;
	glGenBuffers(1, &VBO_normals);
	glBindBuffer(GL_ARRAY_BUFFER, VBO_normals);
	glBufferData(GL_ARRAY_BUFFER, normals.size() * sizeof(GLfloat), &normals[0], GL_STATIC_DRAW);
	glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, 0, 0);
	glEnableVertexAttribArray(1);

	//textures----------------------------------------------------------------------------------------------------
	unsigned int texture;
	glGenTextures(1, &texture);
	glBindTexture(GL_TEXTURE_2D, texture);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR_MIPMAP_LINEAR);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);
	glTexImage2D(GL_TEXTURE_2D, 0, GL_RGB, imgWidth, imgHeight, 0, GL_RGB, GL_UNSIGNED_BYTE, img);
	glGenerateMipmap(GL_TEXTURE_2D);

	unsigned int VBO_texture;
	glGenBuffers(1, &VBO_texture);
	glBindBuffer(GL_ARRAY_BUFFER, VBO_texture);
	glBufferData(GL_ARRAY_BUFFER, texCoordinates.size() * sizeof(GLfloat), &texCoordinates[0], GL_STATIC_DRAW);
	glVertexAttribPointer(2, 2, GL_FLOAT, GL_FALSE, 0, (void*)0);
	glEnableVertexAttribArray(2);
	
	//camera----------------------------------------------------------------------------------------------------

	//perspective matrix
	float aspect = (float)width / (float)height;
	float near = 1, far = 100, fov = 45;
	//glm::mat4 proj = glm::perspective(glm::radians(fov), aspect, near, far);

	//positioning
	cameraPos = glm::vec3(0.0f, 0.0f, Radius * 5.0f);

	//direction
	glm::vec3 cameraTarget = glm::vec3(0.0f, 0.0f, 0.0f); //point to the origin of our scene
	glm::vec3 cameraDirectionVec = glm::normalize(cameraPos - cameraTarget); //get the vector to point in the positive z 

	//specify the up vector
	glm::vec3 up = glm::vec3(0.0f, 1.0f, 0.0f);

	//right vector will be the cross product of our up vector and the direction vector
	glm::vec3 cameraRightVec = glm::normalize(glm::cross(up, cameraDirectionVec));

	//get the camera up vector, we have the right and direction vector, cross product will result in the up vec
	cameraUp = glm::cross(cameraDirectionVec, cameraRightVec);
	cameraFront = glm::vec3(0.0f, 0.0f, -1.0f);

	//-------------------------------------------------------------------------------------------------------------------//
	//-------------------------------------------------------------------------------------------------------------------//
	////reseting all bindings
	glBindVertexArray(0);
	glBindBuffer(GL_ARRAY_BUFFER, 0);
	glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0);

	unsigned int completeShaderProg = compileCompleteShaders((const char*)vertexShaderProg.c_str(), (const char*)fragmentShaderProg.c_str()); //compile all the shaders
	glUseProgram(completeShaderProg);
	glm::mat4 projection = glm::perspective(glm::radians(45.0f), (float)width / (float)height, 0.1f, 100.0f);
	glUniformMatrix4fv(glGetUniformLocation(completeShaderProg, "projection"), 1, GL_FALSE, &projection[0][0]);

	//lighting-----------------------------------------------------------------------------------------------------------//
	lightPos = glm::vec4(cameraPos.x, cameraPos.y, cameraPos.z, 1.0f);
	glUniform4fv(glGetUniformLocation(completeShaderProg, "light"), 1, &lightPos[0]);

	//set camerapos 
	/*glUniform3fv(glGetUniformLocation(completeShaderProg, "cameraPosition"), 1, &cameraPos[0]);*/

	glEnable(GL_DEPTH_TEST);	
	
	//render loop
	while (!glfwWindowShouldClose(window))
	{
		//input
		processInput(window);

		//render
		glClearColor(0.0f, 0.0f, 0.0f, 0.0f);
		glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

		//activate shader program
		glUseProgram(completeShaderProg);

		//assigning of the view and projection matrices to uniform shader variables
		glm::mat4 view = glm::mat4(1.0f); // make sure to initialize matrix to identity matrix first

		view = glm::lookAt(cameraPos, glm::vec3(0.0f, 0.0f, 0.0f), cameraUp);//eye point, center (look at point), and up vector
		glUniformMatrix4fv(glGetUniformLocation(completeShaderProg, "view"), 1, GL_FALSE, &view[0][0]);

		//world transformations
		glm::mat4 model = glm::mat4(1.0f);
		glUniformMatrix4fv(glGetUniformLocation(completeShaderProg, "model"), 1, GL_FALSE, &model[0][0]);

		//image
		glActiveTexture(GL_TEXTURE0);
		glBindTexture(GL_TEXTURE_2D, texture);
		glUniform1i(glGetUniformLocation(completeShaderProg, "diffuseTex"), 0);

		//lightPos
		glUniform4fv(glGetUniformLocation(completeShaderProg, "light"), 1, &lightPos[0]);

		//set Ks 
		glUniform1f(glGetUniformLocation(completeShaderProg, "Ks"), Ks);

		//set Kd
		glUniform1f(glGetUniformLocation(completeShaderProg, "Kd"), Kd);

		//set shininess
		glUniform1f(glGetUniformLocation(completeShaderProg, "shininess"), shininess);

		//set materialSpecularColor
		glUniform3fv(glGetUniformLocation(completeShaderProg, "materialSpecularColor"), 1, &matSpecColor[0]);
		
		//bindings
		glBindVertexArray(VAO);
		glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, EBO);

		//render
		glDrawElements(GL_TRIANGLES, indices.size(), GL_UNSIGNED_INT, NULL);

		glBindVertexArray(0); //reset binding

		// check and call events and swap the buffers
		glfwSwapBuffers(window);
		glfwPollEvents();
	}

	//now delete the individual shader objects once we've linked them into the program object, we don't need them anymore
	//glDeleteShader(vertexShader);
	//glDeleteShader(fragmentShader);

	glDeleteProgram(completeShaderProg);
	glDeleteVertexArrays(1, &VAO);
	glDeleteBuffers(1, &VBO);

	glfwTerminate();
	return 0;
}

void framebuffer_size_callback(GLFWwindow* window, int width, int height)
{
	glViewport(0, 0, width, height);
}

void processInput(GLFWwindow* window)
{
	const float cameraSpeed = 0.05f; // adjust accordingly

	//ESC
	if (glfwGetKey(window, GLFW_KEY_ESCAPE) == GLFW_PRESS)
		glfwSetWindowShouldClose(window, true);

	//camera controls ---------------------------------------/
	//W
	if (glfwGetKey(window, GLFW_KEY_W) == GLFW_PRESS)
	{
		pitch += (1.0f * cameraSpeed);
	}
	//S
	if (glfwGetKey(window, GLFW_KEY_S) == GLFW_PRESS)
	{
		pitch -= (1.0f * cameraSpeed);
	}
	//A
	if (glfwGetKey(window, GLFW_KEY_A) == GLFW_PRESS)
	{
		yaw += (1.0f * cameraSpeed);
	}
	//D
	if (glfwGetKey(window, GLFW_KEY_D) == GLFW_PRESS)
	{
		yaw -= (1.0f * cameraSpeed);
	}	

	//move light position
	//move light left
	if (glfwGetKey(window, GLFW_KEY_F) == GLFW_PRESS)
	{
		Ks -= 0.001;
	}	
	//move light up
	if (glfwGetKey(window, GLFW_KEY_T) == GLFW_PRESS)
	{
		Ks -= 0.001;
	}	
	//move light down
	if (glfwGetKey(window, GLFW_KEY_G) == GLFW_PRESS)
	{
		Ks -= 0.001;
	}	
	//move light right
	if (glfwGetKey(window, GLFW_KEY_H) == GLFW_PRESS)
	{
		Ks -= 0.001;
	}

	//diffuse/specular constants control
	//K - Controls Ks down
	if (glfwGetKey(window, GLFW_KEY_K) == GLFW_PRESS)
	{
		Ks -= 0.001;
	}	
	//L - Controls Ks up 
	if (glfwGetKey(window, GLFW_KEY_L) == GLFW_PRESS)
	{
		Ks += 0.001;
	}	
	//O - Controls Kd down
	if (glfwGetKey(window, GLFW_KEY_O) == GLFW_PRESS)
	{
		Kd -= 0.001;
	}	
	//P - Controls Ks up
	if (glfwGetKey(window, GLFW_KEY_P) == GLFW_PRESS)
	{
		Kd += 0.001;
	}	

	//shininess
	//Z - Controls Shininess down
	if (glfwGetKey(window, GLFW_KEY_Z) == GLFW_PRESS)
	{
		shininess -= 0.01;
	}	
	//X - Controls Shininess up
	if (glfwGetKey(window, GLFW_KEY_X) == GLFW_PRESS)
	{
		shininess += 0.01;
	}

	//light position
	if (glfwGetKey(window, GLFW_KEY_UP) == GLFW_PRESS)
	{
		pitchL += (1.0f * cameraSpeed);

	}	
	if (glfwGetKey(window, GLFW_KEY_DOWN) == GLFW_PRESS)
	{
		pitchL -= (1.0f * cameraSpeed);

	}	
	if (glfwGetKey(window, GLFW_KEY_LEFT) == GLFW_PRESS)
	{
		yawL += (1.0f * cameraSpeed);

	}	
	if (glfwGetKey(window, GLFW_KEY_RIGHT) == GLFW_PRESS)
	{
		yawL -= (1.0f * cameraSpeed);

	}


	//material specular color controls
	//brass
	if (glfwGetKey(window, GLFW_KEY_0) == GLFW_PRESS)
	{
		matSpecColor = glm::vec3(0.992157f, 0.941176f, 0.807843f);
	}
	//bronze
	if (glfwGetKey(window, GLFW_KEY_1) == GLFW_PRESS)
	{
		matSpecColor = glm::vec3(0.393548f, 0.271906f, 0.166721f);
	}
	//chrome
	if (glfwGetKey(window, GLFW_KEY_2) == GLFW_PRESS)
	{
		matSpecColor = glm::vec3(0.774597f, 0.774597f, 0.774597f);
	}
	//copper
	if (glfwGetKey(window, GLFW_KEY_3) == GLFW_PRESS)
	{
		matSpecColor = glm::vec3(0.256777f, 0.137622f, 0.086014f);
	}
	//gold
	if (glfwGetKey(window, GLFW_KEY_4) == GLFW_PRESS)
	{
		matSpecColor = glm::vec3(0.628281f, 0.555802f, 0.366065f);
	}

	if (pitch > 89.0f)
		pitch = 89.0f;
	if (pitch < -89.0f)
		pitch = -89.0f;
	if (Kd >= 0.98)
		Kd = 0.98;
	if (Ks >= 0.98)
		Ks = 0.98;
	if (shininess >= 10.0f)
		shininess = 10.0f;

	camX = (cos(glm::radians(yaw)) * cos(glm::radians(pitch))) * Radius * 3.0f;
	camY = sin(glm::radians(pitch)) * Radius * 3.0f;
	camZ = sin(glm::radians(yaw)) * cos(glm::radians(pitch)) * Radius * 3.0f;

	float lightX, lightY, lightZ;
	lightX = (cos(glm::radians(yawL)) * cos(glm::radians(pitchL))) * Radius * 3.0f;
	lightY = sin(glm::radians(pitchL)) * Radius * 3.0f;
	lightZ = sin(glm::radians(yawL)) * cos(glm::radians(pitchL)) * Radius * 3.0f;

	lightPos = glm::vec4(lightX, lightY, lightZ, 1.0f);

	cameraPos = glm::vec3(camX, camY, camZ);
}

unsigned int compileShader(GLenum shaderType, const char* shaderProgram)
{
	//In order for OpenGL to use the shader it has to dynamically compile it at run - time from its source code.
	unsigned int shader = glCreateShader(shaderType); //define the type of shader we are creating

	//attach the vertex shader source code to the shader object and compile the shader
	glShaderSource(shader, 1, &shaderProgram, NULL);
	//The glShaderSource function takes the shader object to compile to as its first argument. The second argument specifies how many strings we're passing as source code, 
	//	which is only one. The third parameter is the actual source code of the vertex shader and we can leave the 4th parameter to NULL.
	glCompileShader(shader);

	//need to check if compilation of the vertex shader was successful
	int shaderCompiled;
	char log[512];
	//now check if the compilation was successful
	glGetShaderiv(shader, GL_COMPILE_STATUS, &shaderCompiled);

	//retrive the error message and log it, print it 
	if (!shaderCompiled)
	{
		glGetShaderInfoLog(shader, 512, NULL, log);
		std::cout << "ERROR::SHADER::VERTEX::COMPILATION_FAILED\n" << log << std::endl;
	}

	return shader;
}

unsigned int compileCompleteShaders(const char* vertexShader, const char* fragmentShader)
{
	unsigned int vertexCompiled = compileShader(GL_VERTEX_SHADER, vertexShader);
	unsigned int fragmentCompiled = compileShader(GL_FRAGMENT_SHADER, fragmentShader);
	char log[512];

	//now create the final linked version of all shader programs combined. Link all of the shader programs together into one single program, then activate this shader program when rendering objects.

	unsigned int completeShaderProgram = glCreateProgram(); //returns the ID reference to the newly created program object

	//now attach the previously compiled shaders to the program object and then link them
	glAttachShader(completeShaderProgram, vertexCompiled);
	glAttachShader(completeShaderProgram, fragmentCompiled);
	glLinkProgram(completeShaderProgram);

	//now check the success of the linking 
	int completeProgramSuccess;
	glGetProgramiv(completeShaderProgram, GL_LINK_STATUS, &completeProgramSuccess);

	if (!completeProgramSuccess)
	{
		glGetProgramInfoLog(completeShaderProgram, 512, NULL, log);
		std::cout << "ERROR::SHADER::PROGRAM::COMPILATION_FAILED\n" << log << std::endl;
	}

	return completeShaderProgram;
}
