// Author: Ronaldo Engelke Cunha
// Class: CAP 5725
// Assignment: Assignment 1
// Date: 09/09/2022


#include <iostream>
#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/mat4x4.hpp>
#include <glm/common.hpp>
#include <vector>
#include <Math.h>  
#include <cmath>
#include <glm/gtc/type_ptr.hpp>

#define Pi 3.1415926535897932384626433832795

//vertex shader - processes input vertex data, usually normalizes and transforms input data to coordinates that fall within OpenGL's visible region
const char* vertexShaderProg = "#version 330 core\n"
"layout (location = 0) in vec3 position;\n"
"layout (location = 1) in vec3 normal;\n"
"uniform mat4 view, projection;\n"
"out vec3 normalsOutput;\n"
"void main()\n"
"{\n"
"   gl_Position = projection * view * vec4(position, 1.0);\n"
"   normalsOutput = normal;\n"
"}\0";

//fragment shader - calculates the color output of our pixels. Processes a fragment generated by the rasterization stage, into a set of colors and a single depth value.
const char* fragmentShaderProg = "#version 330 core\n"
"in vec3 normalsOutput;\n"
"out vec4 FragmentColor;\n"
"void main()\n"
"{\n"
" FragmentColor = vec4(abs(normalsOutput),1.0);\n"
"}\0";

//line shaders
std::string lineVertexShaderProg = R"(#version 330 core
layout (location = 0) in vec3 position;
uniform mat4 view, projection;
void main()
{
	gl_Position = projection * view * vec4(position, 1.0);
};)";

std::string lineFragmentShaderProg = R"(#version 330 core
uniform vec3 inColor;
out vec4 FragmentColor;
void main()
{
	FragmentColor = vec4(inColor.x, inColor.y, inColor.z, 1.0);
};)";

std::vector<glm::vec3> tempVertices;
std::vector<glm::vec3> normals;
std::vector<glm::vec3> tangents;
std::vector<glm::vec3> bitangents;
std::vector<float> colors;
std::vector<GLfloat> vertices;
std::vector<GLuint> indices;
std::vector<GLuint> normalIndices;

glm::vec3 cameraUp, cameraPos, cameraFront;
float yaw = -90.0f;
float pitch, Radius;
float camX, camY, camZ;

/// <summary>
/// Resize callback function for when window is resized by user. This adjusts the viewpoirt when the user resizes the window.
/// This function takes a window, and new window dimensions as parameters. Whenever the window changes in size, GLFW calls this function and fills in the proper arguments for you to process.
/// </summary>
/// <param name="window"></param>
/// <param name="width"></param>
/// <param name="height"></param>
void framebuffer_size_callback(GLFWwindow* window, int width, int height);

/// <summary>
/// Processes user input.
/// Processes user input.
/// </summary>
/// <param name="window"></param>
void processInput(GLFWwindow* window);

//unsigned int& processVertexArrayObject();
//unsigned int& processVertexBufferObject();
//unsigned int& processElementBufferObject();

unsigned int compileShader(GLenum shaderType, const char* shaderProgram);
unsigned int compileCompleteShaders(const char* vertexShader, const char* fragmentShader);

int main()
{
	glfwInit();
	glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
	glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
	glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

	GLFWwindow* window = glfwCreateWindow(800, 600, "LearnOpenGL", NULL, NULL);

	if (window == NULL)
	{
		std::cout << "Failed to create GLFW window" << std::endl;
		glfwTerminate();
		return -1;
	}

	glfwMakeContextCurrent(window); //tell GLFW to make the context of our window the main context on the current thread

	if (glewInit() != GLEW_OK) //pass GLEW the function to load the address of the OpenGL function pointers which is OS-specific
	{
		std::cout << "Failed to initialize GLEW" << std::endl;
		return -1;
	}
	int width, height;
	width = 800;
	height = 600;
	glViewport(0, 0, width, height);

	glfwSetFramebufferSizeCallback(window, framebuffer_size_callback);

	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	Radius = 1;
	float x, y, z; //coordinates of each vertex
	float u, v; //u represents the unit longitudes of our sphere, v represents the unit latitudes of our sphere
	float Longs = 50;
	float LongsStep; //size of each sector
	float Lats = 50;
	float LatsStep; //size of each stack
	float totalSize = (Longs + 1) * Lats * 2 * 3;

	LongsStep = 2 * Pi / Longs; //calculate the size of each longitude step
	LatsStep = Pi / Lats; //calculate the size of each latitude step

	float LongAngle; //Theta = 2pi * longStep/longCount so also equal to => j * longStep (size)
	float LatAngle; //Phi = (Pi/2 - Pi) * (latStep/latCount) so also equal to => Pi/2 - i * latStep (size)

	const float UnitLat = 1 / (float)(Lats - 1);
	const float UnitLong = 1 / (float)(Longs - 1);

	float normalizedLength = 1.0f;

	int k0, k1, k2;

	std::vector<float> displacementN;
	std::vector<float> displacementT;
	std::vector<float> displacementBT;

	for (int i = 0; i <= Lats; i++)
	{
		LatAngle = (0.5 * Pi) - i * LatsStep;

		k1 = i * (Longs + 1);     // beginning of current stack
		k2 = (i + 1) * (Longs + 1);      // beginning of next stack

		for (int j = 0; j <= Longs; j++)
		{
			LongAngle = j * LongsStep;
			float LongAngleOfNextLong;
			if (j + 1 > Longs)
			{
				LongAngleOfNextLong = 0;
			}
			else 
			{
				LongAngleOfNextLong = (j + 1) * LongsStep;
			}
			float x1, y1, z1;

			//vertex positions
			x = Radius * cos(LatAngle) * cos(LongAngle);
			y = Radius * cos(LatAngle) * sin(LongAngle);
			z = Radius * sin(LatAngle);

			x1 = Radius * cos(LatAngle) * cos(LongAngleOfNextLong);
			y1 = Radius * cos(LatAngle) * sin(LongAngleOfNextLong);
			z1 = Radius * sin(LatAngle);
			glm::vec3 nextLong(x1, y1, z1);

			vertices.push_back(x);
			vertices.push_back(y);
			vertices.push_back(z);

			//if(x == )

			//also add a vertex object to the tempVertices list
			glm::vec3 temp(x, y, z);
			tempVertices.push_back(temp);

			//also add the normal vector
			glm::vec3 normal((x * (1.0f) / Radius), (y * (1.0f) / Radius), (z * (1.0f)) / Radius);

			glm::vec3 displacedAlongN = (temp + (normal * 0.03f));

			displacementN.push_back(temp.x); //vertex
			displacementN.push_back(temp.y); //vertex
			displacementN.push_back(temp.z); //vertex
			displacementN.push_back(displacedAlongN.x); //displaced vertex along normal
			displacementN.push_back(displacedAlongN.y); //displaced vertex along normal
			displacementN.push_back(displacedAlongN.z); //displaced vertex along normal

			colors.push_back(0.3f);
			colors.push_back(0.9f);
			colors.push_back(0.3f);			
			
			colors.push_back(0.3f);
			colors.push_back(0.9f);
			colors.push_back(0.3f);

			normals.push_back(normal);

			//tangent + bitangent 
			// k1 --- k1+1 ---- k1+2 etc.
			glm::vec3 displacedAlongLongitude = (temp + nextLong);
			//now do cross product
			glm::vec3 TangentVec = glm::cross(normal, displacedAlongLongitude);
			//do the displacement
			glm::vec3 displacedAlongT = (temp + (TangentVec * 0.07f));
			displacementN.push_back(temp.x);
			displacementN.push_back(temp.y);
			displacementN.push_back(temp.z);
			displacementN.push_back(displacedAlongT.x);
			displacementN.push_back(displacedAlongT.y);
			displacementN.push_back(displacedAlongT.z);

			colors.push_back(0.1f);
			colors.push_back(0.4f);
			colors.push_back(0.8f);			
			
			colors.push_back(0.1f);
			colors.push_back(0.4f);
			colors.push_back(0.8f);

			//now cross this the tangent vector with the normal, you will then get the bitangent
			glm::vec3 BitangentVec = glm::cross(normal, TangentVec);
			glm::vec3 displacedAlongBT = (temp + (BitangentVec * 0.07f));
			displacementN.push_back(temp.x);
			displacementN.push_back(temp.y);
			displacementN.push_back(temp.z);
			displacementN.push_back(displacedAlongBT.x);
			displacementN.push_back(displacedAlongBT.y);
			displacementN.push_back(displacedAlongBT.z);

			colors.push_back(0.9f);
			colors.push_back(0.1f);
			colors.push_back(0.1f);			
			
			colors.push_back(0.9f);
			colors.push_back(0.1f);
			colors.push_back(0.1f);
			

			float ax = glm::dot(displacedAlongN, displacedAlongBT);
			float ay = glm::dot(displacedAlongN, displacedAlongT);
		}
	}
	int counter = 0;

	for (int i = 0; i <= Lats; i++)
	{
		k1 = i * (Longs + 1);     // beginning of current stack
		k2 = (i + 1) * (Longs + 1);      // beginning of next stack

		for (int j = 0; j <= Longs; j++, counter++, k1++, k2++)
		{
			//must draw our triangles, then draw our TBN vector protrouding out

			// 2 triangles per sector excluding first and last stacks
			if (i != 0)
			{
				indices.push_back(k1);
				indices.push_back(k2);
				indices.push_back(k1 + 1);
			}

			if (i != (Lats))
			{
				indices.push_back(k1 + 1);
				indices.push_back(k2);
				indices.push_back(k2 + 1);
			}
		}
	}

	unsigned int VAO;
	glGenVertexArrays(1, &VAO);
	glBindVertexArray(VAO);

	unsigned int VBO;
	glGenBuffers(1, &VBO);
	glBindBuffer(GL_ARRAY_BUFFER, VBO);
	glBufferData(GL_ARRAY_BUFFER, vertices.size() * sizeof(GLfloat), &vertices[0], GL_STATIC_DRAW);

	GLint vertexPositionAttribute;

	glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 0, 0);
	glEnableVertexAttribArray(0);

	unsigned int normalsBuffer;
	glGenBuffers(1, &normalsBuffer);
	glBindBuffer(GL_ARRAY_BUFFER, normalsBuffer);
	glBufferData(GL_ARRAY_BUFFER, normals.size() * sizeof(glm::vec3), &normals[0], GL_STATIC_DRAW);
	glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, 0, 0);
	glEnableVertexAttribArray(1);

	unsigned int EBO;
	glGenBuffers(1, &EBO);
	glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, EBO);
	glBufferData(GL_ELEMENT_ARRAY_BUFFER, indices.size() * sizeof(GLuint), &indices[0], GL_STATIC_DRAW);

	//line drawing------------------------------------------------
		//normal
	unsigned int VAOlineN;
	glGenVertexArrays(1, &VAOlineN);
	glBindVertexArray(VAOlineN);

	unsigned int VBOlineN;
	glGenBuffers(1, &VBOlineN);
	glBindBuffer(GL_ARRAY_BUFFER, VBOlineN);
	glBufferData(GL_ARRAY_BUFFER, displacementN.size() * sizeof(GLfloat), &displacementN[0], GL_STATIC_DRAW);

	glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 0, 0);
	glEnableVertexAttribArray(0);

	//camera----------------------------------------------------------------------------------------------------

	//perspective matrix
	float aspect = (float)width / (float)height;
	float near = 1, far = 100, fov=45;
	//glm::mat4 proj = glm::perspective(glm::radians(fov), aspect, near, far);

	//positioning
	cameraPos = glm::vec3(0.0f, 0.0f, Radius * 5.0f);

	//direction
	glm::vec3 cameraTarget = glm::vec3(0.0f, 0.0f, 0.0f); //point to the origin of our scene
	glm::vec3 cameraDirectionVec = glm::normalize(cameraPos - cameraTarget); //get the vector to point in the positive z 

	//specify the up vector
	glm::vec3 up = glm::vec3(0.0f, 1.0f, 0.0f);

	//right vector will be the cross product of our up vector and the direction vector
	glm::vec3 cameraRightVec = glm::normalize(glm::cross(up, cameraDirectionVec));

	//get the camera up vector, we have the right and direction vector, cross product will result in the up vec
	cameraUp = glm::cross(cameraDirectionVec, cameraRightVec);
	cameraFront = glm::vec3(0.0f, 0.0f, -1.0f);

	/////////////////////////////////////////

	////reseting all bindings
	glBindVertexArray(0);
	glBindBuffer(GL_ARRAY_BUFFER, 0);
	glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0);

	unsigned int completeShaderProg = compileCompleteShaders(vertexShaderProg, fragmentShaderProg); //compile all the shaders
	unsigned int completeLineShaderProg = compileCompleteShaders((const char*)lineVertexShaderProg.c_str(), (const char*)lineFragmentShaderProg.c_str()); //compile all the shaders

	glUseProgram(completeShaderProg);
	glm::mat4 projection = glm::perspective(glm::radians(45.0f), (float)width / (float)height, 0.1f, 100.0f);
	glUniformMatrix4fv(glGetUniformLocation(completeShaderProg, "projection"), 1, GL_FALSE, &projection[0][0]);

	glUseProgram(completeLineShaderProg);
	glUniformMatrix4fv(glGetUniformLocation(completeLineShaderProg, "projection"), 1, GL_FALSE, &projection[0][0]);

	//render loop
	while (!glfwWindowShouldClose(window))
	{
		//input
		processInput(window);

		//render
		glClearColor(0.0f, 0.0f, 0.0f, 0.0f);
		glClear(GL_COLOR_BUFFER_BIT);

		//activate shader program
		glUseProgram(completeShaderProg);

		//assigning of the view and projection matrices to uniform shader variables
		glm::mat4 view = glm::mat4(1.0f); // make sure to initialize matrix to identity matrix first

		view = glm::lookAt(cameraPos, glm::vec3(0.0f,0.0f,0.0f) , cameraUp);//eye point, center (look at point), and up vector
		glUniformMatrix4fv(glGetUniformLocation(completeShaderProg, "view"), 1, GL_FALSE, &view[0][0]);

		//bindings
		glBindVertexArray(VAO);
		glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, EBO);

		//render
		glDrawElements(GL_TRIANGLES, indices.size() * 3, GL_UNSIGNED_INT, NULL);

		glBindVertexArray(0); //reset binding

		//Normals, Tangents, Bitangents------------------------------------------------------------
		
		glUseProgram(completeLineShaderProg);
		glUniformMatrix4fv(glGetUniformLocation(completeLineShaderProg, "view"), 1, GL_FALSE, &view[0][0]);
		glUniform3fv(glGetUniformLocation(completeLineShaderProg, "inColor"), 1, &colors[0]);

		glBindVertexArray(VAOlineN);
		glBindBuffer(GL_ARRAY_BUFFER, VBOlineN);
		glDrawArrays(GL_LINES, 0, displacementN.size());

		// check and call events and swap the buffers
		glfwSwapBuffers(window);
		glfwPollEvents();
	}

	//now delete the individual shader objects once we've linked them into the program object, we don't need them anymore
	//glDeleteShader(vertexShader);
	//glDeleteShader(fragmentShader);

	glDeleteProgram(completeShaderProg);
	glDeleteVertexArrays(1, &VAO);
	glDeleteBuffers(1, &VBO);

	glfwTerminate();
	return 0;
}

void framebuffer_size_callback(GLFWwindow* window, int width, int height)
{
	glViewport(0, 0, width, height);
}

void processInput(GLFWwindow* window)
{
	const float cameraSpeed = 0.05f; // adjust accordingly

	//ESC
	if (glfwGetKey(window, GLFW_KEY_ESCAPE) == GLFW_PRESS)
		glfwSetWindowShouldClose(window, true);
	//W
	if (glfwGetKey(window, GLFW_KEY_W) == GLFW_PRESS)
	{
		pitch += (1.0f * cameraSpeed);
	}
	//S
	if (glfwGetKey(window, GLFW_KEY_S) == GLFW_PRESS)
	{
		pitch -= (1.0f * cameraSpeed);
	}
	//A
	if (glfwGetKey(window, GLFW_KEY_A) == GLFW_PRESS)
	{
		yaw += (1.0f * cameraSpeed);
	}
	//D
	if (glfwGetKey(window, GLFW_KEY_D) == GLFW_PRESS)
	{
		yaw -= (1.0f * cameraSpeed);
	}

	if (pitch > 89.0f)
		pitch = 89.0f;
	if (pitch < -89.0f)
		pitch = -89.0f;

	camX = (cos(glm::radians(yaw)) * cos(glm::radians(pitch))) * Radius * 3.0f;
	camY = sin(glm::radians(pitch)) * Radius *3.0f;
	camZ = sin(glm::radians(yaw)) * cos(glm::radians(pitch)) * Radius * 3.0f;

	cameraPos = glm::vec3(camX, camY, camZ);
}

unsigned int compileShader(GLenum shaderType, const char* shaderProgram)
{

	//In order for OpenGL to use the shader it has to dynamically compile it at run - time from its source code.
	unsigned int shader = glCreateShader(shaderType); //define the type of shader we are creating

	//attach the vertex shader source code to the shader object and compile the shader
	glShaderSource(shader, 1, &shaderProgram, NULL);
	//The glShaderSource function takes the shader object to compile to as its first argument. The second argument specifies how many strings we're passing as source code, 
	//	which is only one. The third parameter is the actual source code of the vertex shader and we can leave the 4th parameter to NULL.
	glCompileShader(shader);

	//need to check if compilation of the vertex shader was successful
	int shaderCompiled;
	char log[512];
	//now check if the compilation was successful
	glGetShaderiv(shader, GL_COMPILE_STATUS, &shaderCompiled);

	//retrive the error message and log it, print it 
	if (!shaderCompiled)
	{
		glGetShaderInfoLog(shader, 512, NULL, log);
		std::cout << "ERROR::SHADER::VERTEX::COMPILATION_FAILED\n" << log << std::endl;
	}

	return shader;
}


unsigned int compileCompleteShaders(const char* vertexShader, const char* fragmentShader)
{

	unsigned int vertexCompiled = compileShader(GL_VERTEX_SHADER, vertexShader);
	unsigned int fragmentCompiled = compileShader(GL_FRAGMENT_SHADER, fragmentShader);
	char log[512];

	//now create the final linked version of all shader programs combined. Link all of the shader programs together into one single program, then activate this shader program when rendering objects.

	unsigned int completeShaderProgram = glCreateProgram(); //returns the ID reference to the newly created program object

	//now attach the previously compiled shaders to the program object and then link them
	glAttachShader(completeShaderProgram, vertexCompiled);
	glAttachShader(completeShaderProgram, fragmentCompiled);
	glLinkProgram(completeShaderProgram);

	//now check the success of the linking 
	int completeProgramSuccess;
	glGetProgramiv(completeShaderProgram, GL_LINK_STATUS, &completeProgramSuccess);

	if (!completeProgramSuccess)
	{
		glGetProgramInfoLog(completeShaderProgram, 512, NULL, log);
		std::cout << "ERROR::SHADER::PROGRAM::COMPILATION_FAILED\n" << log << std::endl;
	}

	return completeShaderProgram;
}
